### ISSUE TITLE
how to use this lib

### ISSUE THREAD

**Issue by j-w-huang** [yiskang/react-ribbon#1]
can you give me for the demo's source,
I like your wonderful work,
Thank you!

**Comment by yiskang** [comment]
Hi~ @j-w-huang,

You are free to access the demo sources from [test/js](../tree/master/test/src/js) folder.

I will add more usage example as soon as possible if it's not enough.

Hope you enjoy it ~ :)

**Comment by yiskang** [comment]
Hi~ @j-w-huang,

I've updated all documents and examples for this repository.

Now it can be accessed via <a href="http://yiskang.github.io/react-ribbon/doc" target="_blank">here</a>.

I'm going to close this issue now!!

**Comment by j-w-huang** [comment]
Thank you. I've coded a suite like this.
But, I also enjoy your work ...
